language: python

python:
  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install tox-travis
  - pip install coveralls

script:
  - tox
  - coverage report -m

after_success:
  - coveralls
