language: python

python:
  - "2.7"
  - "3.5"
  - "3.6.3"
  - "3.7.2"

install:
  - pip install -r requirements.txt
  - pip install tox-travis
  - pip install coveralls

script:
  - tox
  - coverage report -m

after_success:
  - coveralls
